### ISSUE TITLE
[Feature Request] Does ServerlessLLM have an official docker image？

### ISSUE THREAD

**Issue by dblate** [ServerlessLLM/ServerlessLLM#125] opened 2024-10-28 07:50 UTC
### Prerequisites

- [X] I have searched existing issues and reviewed documentation.

### Problem Description

During quick start  guide（https://serverlessllm.github.io/docs/stable/getting_started/quickstart）, it's better to run in a official docker image, to prevent some env bug.

### Proposed Solution

provide official docker image

### Importance

Nice to have

**Comment by SecretSettler** [comment] 2024-10-28 08:52
Hi,

We have a guide on installing and building ServerlessLLM from scratch using Docker, available here: [https://serverlessllm.github.io/docs/stable/getting_started/docker_quickstart](url). Although we don’t have an official Docker image yet, stay tuned—We are working on it!

**Comment by future-xy** [comment] 2024-10-28 09:51
Thank you for your feature request! It seems that this request is closely related to #113, which also discusses the need for an official Docker image and further enhancements for container-based deployment.

To keep the discussion centralized, I’ll close this issue as a duplicate of #113. Please feel free to add any additional comments or suggestions directly in #113, so we can track all related input in one place.

Thanks again for your input, and we look forward to your continued feedback!

**Closed** 2024-10-28 10:04 UTC
Labels: Duplicate, New feature
